network_boot_nodes = ["/ip4/54.219.26.22/udp/1234/p2p/16Uiu2HAmTVDGNhkHD98zDnJxQWu3i1FL1aFYeh9wiQTNu4pDCgps","/ip4/52.52.127.117/udp/1234/p2p/16Uiu2HAkzRjxK2gorngB1Xq84qDrT4hSVznYDHj6BkbaE4SGx9oS","/ip4/18.167.69.68/udp/1234/p2p/16Uiu2HAm2k6ua2mGgvZ8rTMV8GhpW71aVzkQWy7D37TTDuLCpgmX"]

log_contract_address = "0xbD2C3F0E65eDF5582141C35969d66e34629cC768"

log_sync_start_block_number = 595059

#confirmation_block_count = 6

rpc_enabled = true

rpc_listen_address = "0.0.0.0:5678"
log_config_file = "/app/log_config"

log_directory = "/app/log"

mine_contract_address = "0x6815F41019255e00D6F34aAB8397a6Af5b6D806f"
reward_contract_address = "0x51998C4d486F406a788B766d93510980ae1f9360"
db_max_num_chunks = 1000000000

[sync]

auto_sync_enabled = true
[router]
batcher_file_capacity = 10
batcher_announcement_capacity = 100

